# Etapa 1 - Build
FROM node:18 AS builder

WORKDIR /app

# Copia tudo (incluindo packages, apps, tsconfig.base.json etc)
COPY . .

# Instala dependências do monorepo
RUN npm install --legacy-peer-deps

# Entra na pasta do app-shell e roda build
WORKDIR /app/apps/app-shell
RUN npm run build

# Etapa 2 - Servidor NGINX
FROM nginx:alpine
COPY --from=builder /app/apps/app-shell/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
